spring.datasource.url: jdbc:h2:file:./camunda-h2-database;DB_CLOSE_ON_EXIT=false
server.port: 8100

camunda.bpm.filter.create: All
camunda.bpm.license-file: file:${HOME}/camunda/license.txt

spring.main.allow-bean-definition-overriding: true
camunda.bpm.admin-user:
  id: demo
  password: demo

